[workspace]
resolver = "2"
members = [
    "shared",
    "egui-frontend",
]

[profile.dev]
opt-level = 1  # Faster debug builds for better egui performance

[profile.release]
opt-level = 3
lto = true     # Link-time optimization for smaller binaries
